apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scwvuecom-persistent-storage
  labels:
    app: scwvuecom
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
