apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scwvuecom
  name: scwvuecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scwvuecom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scwvuecom
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: scwvuecom
            topologyKey: kubernetes.io/hostname      
      containers:
      - image: jkozik/scwvue.com:v2.6
        imagePullPolicy: IfNotPresent
        name: scwvuecom
        ports:
        - containerPort: 80
          name: scwvuecom
        resources:
          limits:
            ephemeral-storage: 200M
            memory: 200M
          requests:
            ephemeral-storage: 100M
            memory: 100M
        volumeMounts:
        - mountPath: /var/www/html/mount
          name: scwvuecom-persistent-storage
      volumes:
      - name: scwvuecom-persistent-storage
        persistentVolumeClaim:
          claimName: scwvuecom-persistent-storage

