apiVersion: v1
kind: PersistentVolume
metadata:
  name: scwvuecom-persistent-storage
  labels:
    app: scwvuecom
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.100.153
    # Exported path of your NFS server
    #     path: "/var/nfsshare/nginxhtml"  # make sure this directory exists.
    path: "/home/nfs/weather-stations/sancap/public_html"
  storageClassName: nfs-weather
